In [2]:
import nltk

In [25]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [26]:
## Data Collection

In [3]:
from nltk.corpus import brown

In [28]:
brown?


In [4]:
print(brown.categories())

['adventure', 'belles_lettres', 'editorial', 'fiction', 'government', 'hobbies', 'humor', 'learned', 'lore', 'mystery', 'news', 'religion', 'reviews', 'romance', 'science_fiction']


In [5]:
data = brown.sents(categories= 'editorial')[:100]

In [6]:
print(data[0])

['Assembly', 'session', 'brought', 'much', 'good']


In [7]:
print(len(data))

100


# Basic NLP pipeline

In [8]:
## Tokenization

In [9]:
text = "It was a very pleasant days, the weather was cool and there were light showers. I went to the market to buy some fruits."
print(text)

It was a very pleasant days, the weather was cool and there were light showers. I went to the market to buy some fruits.


In [10]:
from nltk.tokenize import sent_tokenize,word_tokenize 

In [11]:
sents = sent_tokenize(text)
print(sents)

['It was a very pleasant days, the weather was cool and there were light showers.', 'I went to the market to buy some fruits.']


In [12]:
word_list = word_tokenize(sents[0].lower())
print(word_list)

['it', 'was', 'a', 'very', 'pleasant', 'days', ',', 'the', 'weather', 'was', 'cool', 'and', 'there', 'were', 'light', 'showers', '.']


### Stopword Removal

In [13]:
from nltk.corpus import stopwords



print(len(sw))

179


In [14]:
useful_word = [w for w in word_list if w not in sw]
print(useful_word)

['pleasant', 'days', ',', 'weather', 'cool', 'light', 'showers', '.']


In [36]:
def filter_words(words_list):
    
    sw = set(stopwords.words('english'))
    filtered_words = [w for w in words_list if w not in sw]
    return filtered_words

In [15]:
from nltk.tokenize import RegexpTokenizer

In [22]:
tokenizer = RegexpTokenizer("[a-zA-Z@]+")

In [23]:
text = "Send all 50 documents to 1,2,3 at abc@xyz.com"

In [24]:
print(tokenizer.tokenize(text))

['Send', 'all', 'documents', 'to', 'at', 'abc@xyz', 'com']


## Stemming

- Process all verbs into radical form
- without increas number if token
- jumps, jumping => jump

In [30]:
text = """Foxes love to make jumps. The quick brown fox was seen jumping over the lovely dog from a 6ft feet high wall"""

In [32]:
words_list = tokenizer.tokenize(text.lower())

print(words_list)

['foxes', 'love', 'to', 'make', 'jumps', 'the', 'quick', 'brown', 'fox', 'was', 'seen', 'jumping', 'over', 'the', 'lovely', 'dog', 'from', 'a', 'ft', 'feet', 'high', 'wall']


In [38]:
words_list = filter_words(words_list) #remove the stop words
print(words_list)

['foxes', 'love', 'make', 'jumps', 'quick', 'brown', 'fox', 'seen', 'jumping', 'lovely', 'dog', 'ft', 'feet', 'high', 'wall']


## Stemming


In [39]:
# 1- Snowball, Porter, Lancaster Stemmer

In [40]:
#Snowball - support for multi lingual language

In [54]:
from nltk.stem.snowball import PorterStemmer, SnowballStemmer
from nltk.stem.lancaster import LancasterStemmer

In [45]:
ps = PorterStemmer()

ps.stem("loving")

'love'

In [46]:
ps.stem("awesome")

'awesom'

In [47]:
words_list = [ps.stem(w) for w in words_list]

In [48]:
words_list

['fox',
 'love',
 'make',
 'jump',
 'quick',
 'brown',
 'fox',
 'seen',
 'jump',
 'love',
 'dog',
 'ft',
 'feet',
 'high',
 'wall']

In [53]:
ls = LancasterStemmer()

ls.stem("teeth")
print(ps.stem("teenager"))
print(ls.stem("teenager"))

teenag
teen


In [57]:
ss = SnowballStemmer('french')
ss.stem("bonjour")

'bonjour'

In [ ]:
## One function which performs all the three steps - Tokenization, Stopword removal, Remove Leading Trailing white spaces

In [82]:
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords
from nltk.stem.snowball import SnowballStemmer


In [83]:
def txt_prep(input_data): ## Single input data like line or paragraph for one output

    
    tokenizer = RegexpTokenizer("[a-zA-Z@]+")

    word_list = tokenizer.tokenize(input_data)
        
        
    sw = set(stopwords.words('english'))
    word_list = [w for w in words_list if w not in sw]
    
    
    ss = SnowballStemmer('english')
    
    word_list = [ss.stem(w) for w in word_list]
    
    return word_list
    

In [84]:
txt_prep("""Foxes love to make jumps. The quick brown fox was seen jumping over the lovely dog from a 6ft feet high wall""")

['fox',
 'love',
 'make',
 'jump',
 'quick',
 'brown',
 'fox',
 'seen',
 'jump',
 'love',
 'dog',
 'ft',
 'feet',
 'high',
 'wall']

In [85]:
#Try lemmatizer
from nltk.stem import WordNetLemmatizer

l = WordNetLemmatizer()
l.lemmatize("crying")

LookupError: 
**********************************************************************
  Resource wordnet not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('wordnet')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/wordnet

  Searched in:
    - '/home/golu/nltk_data'
    - '/home/golu/anaconda3/nltk_data'
    - '/home/golu/anaconda3/share/nltk_data'
    - '/home/golu/anaconda3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


# Building Common Vocab using Bag of words

In [86]:
corpus = [
    'Indian Cricket team will win World Cup, says Capt. Virat Kohli.',
    'We will win next Lok Sabha Elections, says confident Indian PM',
    'The nobel lauretes won the heart of the people.',
    'The movie raazi is an exciting Indian Spy thriller based upon a real story'
]

In [87]:
from sklearn.feature_extraction.text import CountVectorizer

In [88]:
cv = CountVectorizer()

In [96]:
vectorized_corpus = cv.fit_transform(corpus).toarray()

In [100]:
vectorized_corpus

array([[0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1],
       [0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 1, 0],
       [1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
        0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0]])

In [99]:
print(cv.vocabulary_)

{'indian': 9, 'cricket': 4, 'team': 26, 'will': 32, 'win': 33, 'world': 35, 'cup': 5, 'says': 23, 'capt': 2, 'virat': 30, 'kohli': 11, 'we': 31, 'next': 15, 'lok': 13, 'sabha': 22, 'elections': 6, 'confident': 3, 'pm': 19, 'the': 27, 'nobel': 16, 'lauretes': 12, 'won': 34, 'heart': 8, 'of': 17, 'people': 18, 'movie': 14, 'raazi': 20, 'is': 10, 'an': 0, 'exciting': 7, 'spy': 24, 'thriller': 28, 'based': 1, 'upon': 29, 'real': 21, 'story': 25}


In [107]:
import numpy as np
#Given a vector what is sentence?

print(vectorized_corpus.shape)

vec = np.ones((36,))
vec[3:7] = 0
vec

(4, 36)


array([1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1.])

In [108]:
cv.inverse_transform(vec)

[array(['an', 'based', 'capt', 'exciting', 'heart', 'indian', 'is',
        'kohli', 'lauretes', 'lok', 'movie', 'next', 'nobel', 'of',
        'people', 'pm', 'raazi', 'real', 'sabha', 'says', 'spy', 'story',
        'team', 'the', 'thriller', 'upon', 'virat', 'we', 'will', 'win',
        'won', 'world'], dtype='<U9')]

In [112]:
cv.vocabulary_["the"]

27

In [115]:
#vector len will be equal to size of dictionary
#therefore reduce size of vector effective


In [118]:
def myTokenizer(sentence):
    words = tokenizer.tokenize(sentence.lower())
    return filter_words(words)

In [119]:
myTokenizer(corpus[0])

['indian',
 'cricket',
 'team',
 'win',
 'world',
 'cup',
 'says',
 'capt',
 'virat',
 'kohli']

In [120]:
cv = CountVectorizer(tokenizer = myTokenizer)
vectorized_corpus = cv.fit_transform(corpus)

In [126]:
vc = vectorized_corpus.toarray()
print(vc)
print(len(vc[0]))

v = vc[0]
cv.inverse_transform(v)

[[0 1 0 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 1 1]
 [0 0 1 0 0 1 0 0 1 0 0 1 0 1 0 0 1 0 0 1 1 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1 1 0 0 1 1 0 1 1 0 0 0]]
29


[array(['capt', 'cricket', 'cup', 'indian', 'kohli', 'says', 'team',
        'virat', 'win', 'world'], dtype='<U9')]

# Unigram: Bag of Words model

In [128]:
#Word with single meaning (I dont like ice-cream.) Here dont and like are differebt and show different meaning

In [130]:
## Similarly have bigram and ngram model( just specify parameter in countvector)

In [137]:
cv2 = CountVectorizer(tokenizer = myTokenizer,ngram_range=(1,2))
vc2 = cv2.fit_transform(corpus)

print(cv2.vocabulary_)

{'indian': 16, 'cricket': 6, 'team': 45, 'win': 53, 'world': 56, 'cup': 8, 'says': 39, 'capt': 2, 'virat': 51, 'kohli': 20, 'indian cricket': 17, 'cricket team': 7, 'team win': 46, 'win world': 55, 'world cup': 57, 'cup says': 9, 'says capt': 40, 'capt virat': 3, 'virat kohli': 52, 'next': 27, 'lok': 23, 'sabha': 37, 'elections': 10, 'confident': 4, 'pm': 32, 'win next': 54, 'next lok': 28, 'lok sabha': 24, 'sabha elections': 38, 'elections says': 11, 'says confident': 41, 'confident indian': 5, 'indian pm': 18, 'nobel': 29, 'lauretes': 21, 'heart': 14, 'people': 31, 'nobel lauretes': 30, 'lauretes heart': 22, 'heart people': 15, 'movie': 25, 'raazi': 33, 'exciting': 12, 'spy': 42, 'thriller': 47, 'based': 0, 'upon': 49, 'real': 35, 'story': 44, 'movie raazi': 26, 'raazi exciting': 34, 'exciting indian': 13, 'indian spy': 19, 'spy thriller': 43, 'thriller based': 48, 'based upon': 1, 'upon real': 50, 'real story': 36}
